import React, { useState, useEffect, useRef } from 'react';
import { createChat, sendMessageToChat } from '../../services/geminiService';
import { supabase } from '../../services/supabaseClient';
import { PromptInput } from '../../components/common/PromptInput';
import { Spinner } from '../../components/Spinner';
import { Icon } from '../../components/Icon';
import type { Chat } from '@google/genai';

interface Message {
  sender: 'user' | 'bot';
  text: string;
}

export const Chatbot: React.FC = () => {
  const [chat, setChat] = useState<Chat | null>(null);
  const [sessionId, setSessionId] = useState<string>(() => crypto.randomUUID());
  const [messages, setMessages] = useState<Message[]>([]);
  const [prompt, setPrompt] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isHistoryLoading, setIsHistoryLoading] = useState(true);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setChat(createChat());
  }, [sessionId]); // Re-create chat when session changes

  useEffect(() => {
    const fetchHistory = async () => {
      setIsHistoryLoading(true);
      setFetchError(null);
      const { data, error } = await supabase
        .from('messages')
        .select('sender, text')
        .eq('session_id', sessionId)
        .order('created_at', { ascending: true });

      if (error) {
        console.error('Error fetching chat history:', error.message);
        if (error.message.includes("Could not find the table") || error.message.includes("does not exist")) {
           setFetchError(
            `The 'messages' table was not found in your database.\n\n` +
            `Please run the following SQL query in your Supabase project's SQL Editor to create it:\n\n` +
            `CREATE TABLE public.messages (\n` +
            `  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n` +
            `  created_at timestamp with time zone DEFAULT now() NOT NULL,\n` +
            `  session_id uuid NOT NULL,\n` +
            `  sender text NOT NULL,\n` +
            `  text text NOT NULL\n` +
            `);\n\n` +
            `After creating the table, you may also need to configure Row Level Security (RLS) policies.`
          );
        } else {
          setFetchError(
            `Could not fetch chat history. This is likely due to Row Level Security (RLS) policies on your 'messages' table.\n\n` +
            `Please ensure that RLS is disabled or that a policy is in place to allow anonymous users to read and write messages. You can manage RLS policies in your Supabase project dashboard under Authentication -> Policies.`
          );
        }
        setMessages([]);
      } else {
        setMessages(data as Message[]);
      }
      setIsHistoryLoading(false);
    };

    fetchHistory();
  }, [sessionId]);


  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(scrollToBottom, [messages]);

  const handleSendMessage = async () => {
    if (!chat || prompt.trim() === '') return;

    const userMessageText = prompt;
    const userMessage: Message = { sender: 'user', text: userMessageText };
    setMessages((prev) => [...prev, userMessage]);
    setPrompt('');
    setIsLoading(true);

    try {
      // 1. Save user message
      const { error: userInsertError } = await supabase
        .from('messages')
        .insert({ session_id: sessionId, sender: 'user', text: userMessageText });
      if (userInsertError) throw userInsertError;

      // 2. Get bot response
      const response = await sendMessageToChat(chat, userMessageText);
      const botMessage: Message = { sender: 'bot', text: response.text };
      setMessages((prev) => [...prev, botMessage]);

      // 3. Save bot message
      const { error: botInsertError } = await supabase
        .from('messages')
        .insert({ session_id: sessionId, sender: 'bot', text: response.text });
      if (botInsertError) throw botInsertError;

    } catch (error: any) {
      console.error('An error occurred in the chat flow:', error.message);
      const errorMessage: Message = {
        sender: 'bot',
        text: `Sorry, an error occurred while saving the message. Please check the console for details.`
      };
      setMessages((prev) => [...prev, errorMessage]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleNewChat = () => {
    setMessages([]);
    setFetchError(null);
    setSessionId(crypto.randomUUID());
  };
  
  return (
    <div className="flex flex-col h-full bg-white dark:bg-gray-800 rounded-lg shadow-lg">
      <div className="flex justify-between items-center p-4 border-b border-gray-200 dark:border-gray-700">
        <h2 className="text-xl font-semibold">AI Chatbot</h2>
        <button onClick={handleNewChat} className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-gray-600 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 rounded-md hover:bg-gray-200 dark:hover:bg-gray-600">
          <Icon name="plus" className="w-4 h-4" />
          New Chat
        </button>
      </div>
      <div className="flex-1 p-4 overflow-y-auto">
        {isHistoryLoading ? (
            <div className="flex justify-center items-center h-full">
                <Spinner text="Loading history..." />
            </div>
        ) : fetchError ? (
            <div className="p-4 text-center text-red-600 dark:text-red-400 bg-red-50 dark:bg-red-900/20 rounded-lg">
                <h3 className="font-bold">Database Configuration Error</h3>
                <p className="mt-2 text-sm whitespace-pre-wrap text-left">{fetchError}</p>
            </div>
        ) : (
            <div className="space-y-4">
            {messages.length === 0 && (
                 <div className="flex items-start gap-3">
                    <div className="w-8 h-8 flex-shrink-0 rounded-full bg-primary flex items-center justify-center text-white"><Icon name="spark" className="w-5 h-5"/></div>
                    <div className="px-4 py-2 rounded-lg bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-bl-none">
                        <p className="whitespace-pre-wrap">Hello! How can I help you today?</p>
                    </div>
                </div>
            )}
            {messages.map((msg, index) => (
                <div key={index} className={`flex items-start gap-3 ${msg.sender === 'user' ? 'justify-end' : ''}`}>
                {msg.sender === 'bot' && <div className="w-8 h-8 flex-shrink-0 rounded-full bg-primary flex items-center justify-center text-white"><Icon name="spark" className="w-5 h-5"/></div>}
                <div className={`px-4 py-2 rounded-lg max-w-lg ${msg.sender === 'user' ? 'bg-primary text-white rounded-br-none' : 'bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-bl-none'}`}>
                    <p className="whitespace-pre-wrap">{msg.text}</p>
                </div>
                </div>
            ))}
            {isLoading && (
                <div className="flex items-start gap-3">
                <div className="w-8 h-8 flex-shrink-0 rounded-full bg-primary flex items-center justify-center text-white"><Icon name="spark" className="w-5 h-5"/></div>
                <div className="px-4 py-2 rounded-lg bg-gray-200 dark:bg-gray-700"><Spinner size="sm" /></div>
                </div>
            )}
            <div ref={messagesEndRef} />
            </div>
        )}
      </div>
      <div className="p-4 border-t border-gray-200 dark:border-gray-700">
        <PromptInput
          value={prompt}
          onChange={setPrompt}
          onSubmit={handleSendMessage}
          disabled={isLoading || isHistoryLoading || !!fetchError}
          placeholder="Ask me anything..."
        />
      </div>
    </div>
  );
};